"""empty message

Revision ID: 04a428ec9b89
Revises: 7a5f392a77fb
Create Date: 2026-09-02 17:34:31.216278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04a428ec9b89'
down_revision = '7a5f392a77fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=6), nullable=True))
        batch_op.create_index(batch_op.f('ix_booking_code'), ['code'], unique=False)

    with op.batch_alter_table('queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.Integer(), nullable=True))
        batch_op.alter_column('guest_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue', schema=None) as batch_op:
        batch_op.alter_column('guest_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('number')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_code'))
        batch_op.drop_column('code')

    # ### end Alembic commands ###
