"""empty message

Revision ID: 1f6401e0c54b
Revises: a46c301ad309
Create Date: 2026-09-11 12:39:27.310208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f6401e0c54b'
down_revision = 'a46c301ad309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('license', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entitlements', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('license', schema=None) as batch_op:
        batch_op.drop_column('entitlements')

    # ### end Alembic commands ###
