"""empty message

Revision ID: 29893059fcc2
Revises: cd2cb531dc03
Create Date: 2026-09-07 01:49:22.792657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29893059fcc2'
down_revision = 'cd2cb531dc03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue', schema=None) as batch_op:
        batch_op.alter_column('uid',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    with op.batch_alter_table('table_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sample_object', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_type', schema=None) as batch_op:
        batch_op.drop_column('sample_object')

    with op.batch_alter_table('queue', schema=None) as batch_op:
        batch_op.alter_column('uid',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
