"""empty message

Revision ID: 57200e4ceda8
Revises: bcd804d5bee1
Create Date: 2026-09-05 03:09:24.455884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57200e4ceda8'
down_revision = 'bcd804d5bee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('license', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('system_identifier',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('license', schema=None) as batch_op:
        batch_op.alter_column('system_identifier',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('last_seen_at')

    # ### end Alembic commands ###
