"""empty message

Revision ID: 5948310e6b6e
Revises: 29893059fcc2
Create Date: 2026-09-08 22:59:39.695537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5948310e6b6e'
down_revision = '29893059fcc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lounge_uid', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('table_uid', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue', schema=None) as batch_op:
        batch_op.drop_column('table_uid')
        batch_op.drop_column('lounge_uid')

    # ### end Alembic commands ###
