"""empty message

Revision ID: 67d1a879e305
Revises: 87ef2ec63598
Create Date: 2026-09-04 17:42:49.838595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67d1a879e305'
down_revision = '87ef2ec63598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('license',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('club_uid', sa.String(length=80), nullable=False),
    sa.Column('club_name', sa.String(length=120), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('license', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_license_club_uid'), ['club_uid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('license', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_license_club_uid'))

    op.drop_table('license')
    # ### end Alembic commands ###
