"""baseline schema

Revision ID: 7a5f392a77fb
Revises: 
Create Date: 2026-08-31 07:11:06.118529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a5f392a77fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('date_string', sa.String(length=50), nullable=False),
    sa.Column('lounge', sa.String(length=100), nullable=True),
    sa.Column('table_type', sa.String(length=30), nullable=False),
    sa.Column('table_id', sa.String(length=20), nullable=False),
    sa.Column('player', sa.String(length=100), nullable=False),
    sa.Column('elapsed', sa.String(length=20), nullable=False),
    sa.Column('billable_mins', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('segments_json', sa.Text(), nullable=True),
    sa.Column('canteen_json', sa.Text(), nullable=True),
    sa.Column('play_total', sa.Integer(), nullable=True),
    sa.Column('canteen_total', sa.Integer(), nullable=True),
    sa.Column('split_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('served_by', sa.String(length=80), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.Column('khata_name', sa.String(length=100), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_by', sa.String(length=80), nullable=True),
    sa.Column('bill_group', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_log_bill_group'), ['bill_group'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_closed_at'), ['closed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_customer_id'), ['customer_id'], unique=False)

    op.create_table('canteen_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=20), nullable=False),
    sa.Column('target_label', sa.String(length=60), nullable=True),
    sa.Column('table_uid', sa.String(length=50), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.Column('discount_percent', sa.Integer(), nullable=False),
    sa.Column('discount_amount', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.Column('khata_name', sa.String(length=100), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_by', sa.String(length=80), nullable=True),
    sa.Column('bill_group', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('served_by', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    with op.batch_alter_table('canteen_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_canteen_order_bill_group'), ['bill_group'], unique=False)
        batch_op.create_index(batch_op.f('ix_canteen_order_closed_at'), ['closed_at'], unique=False)

    op.create_table('canteen_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('emoji', sa.String(length=16), nullable=True),
    sa.Column('img_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('canteen_product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_canteen_product_category'), ['category'], unique=False)

    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_phone'), ['phone'], unique=True)

    op.create_table('global_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_type', sa.String(length=50), nullable=False),
    sa.Column('weekday_rate', sa.Integer(), nullable=False),
    sa.Column('weekend_rate', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_type')
    )
    op.create_table('lounge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_intent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('payer_name', sa.String(length=100), nullable=True),
    sa.Column('paid_by', sa.String(length=100), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('log_id', sa.Integer(), nullable=True),
    sa.Column('canteen_order_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_intent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_intent_token'), ['token'], unique=True)

    op.create_table('queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guest_name', sa.String(length=100), nullable=False),
    sa.Column('table_type', sa.String(length=50), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('capabilities', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_uid', sa.String(length=50), nullable=False),
    sa.Column('table_type', sa.String(length=30), nullable=False),
    sa.Column('table_number', sa.Integer(), nullable=True),
    sa.Column('guest_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_session_id'), ['session_id'], unique=False)

    op.create_table('canteen_order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('line_total', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['canteen_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('canteen_order_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_canteen_order_item_order_id'), ['order_id'], unique=False)

    op.create_table('password_reset_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_code', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_code_customer_id'), ['customer_id'], unique=False)

    op.create_table('play_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('play_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_play_session_customer_id'), ['customer_id'], unique=False)

    op.create_table('pool_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=50), nullable=False),
    sa.Column('table_id', sa.String(length=20), nullable=False),
    sa.Column('table_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('booking_name', sa.String(length=100), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('lounge_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lounge_id'], ['lounge.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('session_player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['play_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_player', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_player_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_player_session_id'), ['session_id'], unique=False)

    op.create_table('session_segment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('table_uid', sa.String(length=50), nullable=False),
    sa.Column('table_type', sa.String(length=30), nullable=False),
    sa.Column('table_number', sa.Integer(), nullable=True),
    sa.Column('lounge_name', sa.String(length=100), nullable=True),
    sa.Column('rate', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['play_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_segment')
    with op.batch_alter_table('session_player', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_player_session_id'))
        batch_op.drop_index(batch_op.f('ix_session_player_customer_id'))

    op.drop_table('session_player')
    op.drop_table('pool_table')
    with op.batch_alter_table('play_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_play_session_customer_id'))

    op.drop_table('play_session')
    with op.batch_alter_table('password_reset_code', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_code_customer_id'))

    op.drop_table('password_reset_code')
    with op.batch_alter_table('canteen_order_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_canteen_order_item_order_id'))

    op.drop_table('canteen_order_item')
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_session_id'))
        batch_op.drop_index(batch_op.f('ix_booking_customer_id'))

    op.drop_table('booking')
    op.drop_table('user')
    op.drop_table('queue')
    with op.batch_alter_table('payment_intent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_intent_token'))

    op.drop_table('payment_intent')
    op.drop_table('lounge')
    op.drop_table('global_rate')
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_phone'))

    op.drop_table('customer')
    with op.batch_alter_table('canteen_product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_canteen_product_category'))

    op.drop_table('canteen_product')
    with op.batch_alter_table('canteen_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_canteen_order_closed_at'))
        batch_op.drop_index(batch_op.f('ix_canteen_order_bill_group'))

    op.drop_table('canteen_order')
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_log_customer_id'))
        batch_op.drop_index(batch_op.f('ix_activity_log_closed_at'))
        batch_op.drop_index(batch_op.f('ix_activity_log_bill_group'))

    op.drop_table('activity_log')
    # ### end Alembic commands ###
