"""empty message

Revision ID: 87ef2ec63598
Revises: d3297a70d42f
Create Date: 2026-09-03 15:02:56.182323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87ef2ec63598'
down_revision = 'd3297a70d42f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setting_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('setting_value', sa.Boolean(), nullable=False))
        batch_op.create_unique_constraint(None, ['setting_name'])
        batch_op.drop_column('show_bills_canteen')
        batch_op.drop_column('show_bills_dashboard')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_bills_dashboard', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('show_bills_canteen', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('setting_value')
        batch_op.drop_column('setting_name')

    # ### end Alembic commands ###
