"""empty message

Revision ID: a46c301ad309
Revises: 5948310e6b6e
Create Date: 2026-09-09 20:29:38.942032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a46c301ad309'
down_revision = '5948310e6b6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('license', schema=None) as batch_op:
        batch_op.add_column(sa.Column('server_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('server_checked_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('revoked_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('license', schema=None) as batch_op:
        batch_op.drop_column('revoked_at')
        batch_op.drop_column('server_checked_at')
        batch_op.drop_column('server_status')

    # ### end Alembic commands ###
