"""empty message

Revision ID: b4b6403c126a
Revises: e2c9f1a0dd45
Create Date: 2026-09-19 11:52:03.869090

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b4b6403c126a'
down_revision = 'e2c9f1a0dd45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_log_club_uid'))
        batch_op.drop_column('club_uid')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_club_uid'))
        batch_op.drop_column('club_uid')

    with op.batch_alter_table('branch', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branch_club_uid'))
        batch_op.drop_column('club_uid')

    with op.batch_alter_table('branch_license', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_branch_license_uid'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_branch_license_branch_uid'))
        batch_op.create_index(batch_op.f('ix_branch_license_branch_uid'), ['branch_uid'], unique=True)

    with op.batch_alter_table('canteen_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_canteen_order_club_uid'))
        batch_op.drop_column('club_uid')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('canteen_order_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_canteen_order_item_club_uid'))
        batch_op.drop_column('club_uid')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('canteen_product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_canteen_product_club_uid'))
        batch_op.drop_column('club_uid')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_club_uid'))
        batch_op.drop_column('club_uid')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('global_rate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('global_rate_table_type_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_global_rate_club_uid'))
        batch_op.create_index(batch_op.f('ix_global_rate_branch_id'), ['branch_id'], unique=False)
        batch_op.create_unique_constraint('uq_branch_table_type', ['branch_id', 'table_type'])
        batch_op.create_foreign_key(None, 'branch', ['branch_id'], ['id'])
        batch_op.drop_column('club_uid')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('lounge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lounge_club_uid'))
        batch_op.drop_column('club_uid')

    with op.batch_alter_table('password_reset_code', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_code_club_uid'))
        batch_op.drop_column('club_uid')

    with op.batch_alter_table('payment_intent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_intent_club_uid'))
        batch_op.drop_column('club_uid')

    with op.batch_alter_table('play_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_play_session_club_uid'))
        batch_op.drop_column('club_uid')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('pool_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pool_table_club_uid'))
        batch_op.drop_column('club_uid')

    with op.batch_alter_table('queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_queue_club_uid'))
        batch_op.drop_column('club_uid')

    with op.batch_alter_table('session_player', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_player_club_uid'))
        batch_op.drop_column('club_uid')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('session_segment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_segment_club_uid'))
        batch_op.drop_column('club_uid')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_club_uid'))
        batch_op.drop_column('club_uid')

    with op.batch_alter_table('table_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_table_type_club_uid'))
        batch_op.drop_column('club_uid')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_club_uid'))
        batch_op.drop_column('club_uid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('club_uid', sa.VARCHAR(length=80), server_default=sa.text("current_setting('app.club_uid'::text, true)"), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_user_club_uid'), ['club_uid'], unique=False)

    with op.batch_alter_table('table_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('club_uid', sa.VARCHAR(length=80), server_default=sa.text("current_setting('app.club_uid'::text, true)"), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_table_type_club_uid'), ['club_uid'], unique=False)

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('club_uid', sa.VARCHAR(length=80), server_default=sa.text("current_setting('app.club_uid'::text, true)"), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_settings_club_uid'), ['club_uid'], unique=False)

    with op.batch_alter_table('session_segment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('club_uid', sa.VARCHAR(length=80), server_default=sa.text("current_setting('app.club_uid'::text, true)"), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_session_segment_club_uid'), ['club_uid'], unique=False)

    with op.batch_alter_table('session_player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('club_uid', sa.VARCHAR(length=80), server_default=sa.text("current_setting('app.club_uid'::text, true)"), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_session_player_club_uid'), ['club_uid'], unique=False)

    with op.batch_alter_table('queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('club_uid', sa.VARCHAR(length=80), server_default=sa.text("current_setting('app.club_uid'::text, true)"), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_queue_club_uid'), ['club_uid'], unique=False)

    with op.batch_alter_table('pool_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('club_uid', sa.VARCHAR(length=80), server_default=sa.text("current_setting('app.club_uid'::text, true)"), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_pool_table_club_uid'), ['club_uid'], unique=False)

    with op.batch_alter_table('play_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('club_uid', sa.VARCHAR(length=80), server_default=sa.text("current_setting('app.club_uid'::text, true)"), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_play_session_club_uid'), ['club_uid'], unique=False)

    with op.batch_alter_table('payment_intent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('club_uid', sa.VARCHAR(length=80), server_default=sa.text("current_setting('app.club_uid'::text, true)"), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_payment_intent_club_uid'), ['club_uid'], unique=False)

    with op.batch_alter_table('password_reset_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('club_uid', sa.VARCHAR(length=80), server_default=sa.text("current_setting('app.club_uid'::text, true)"), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_password_reset_code_club_uid'), ['club_uid'], unique=False)

    with op.batch_alter_table('lounge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('club_uid', sa.VARCHAR(length=80), server_default=sa.text("current_setting('app.club_uid'::text, true)"), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_lounge_club_uid'), ['club_uid'], unique=False)

    with op.batch_alter_table('global_rate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('club_uid', sa.VARCHAR(length=80), server_default=sa.text("current_setting('app.club_uid'::text, true)"), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_branch_table_type', type_='unique')
        batch_op.drop_index(batch_op.f('ix_global_rate_branch_id'))
        batch_op.create_index(batch_op.f('ix_global_rate_club_uid'), ['club_uid'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('global_rate_table_type_key'), ['table_type'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('club_uid', sa.VARCHAR(length=80), server_default=sa.text("current_setting('app.club_uid'::text, true)"), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_customer_club_uid'), ['club_uid'], unique=False)

    with op.batch_alter_table('canteen_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('club_uid', sa.VARCHAR(length=80), server_default=sa.text("current_setting('app.club_uid'::text, true)"), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_canteen_product_club_uid'), ['club_uid'], unique=False)

    with op.batch_alter_table('canteen_order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('club_uid', sa.VARCHAR(length=80), server_default=sa.text("current_setting('app.club_uid'::text, true)"), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_canteen_order_item_club_uid'), ['club_uid'], unique=False)

    with op.batch_alter_table('canteen_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('club_uid', sa.VARCHAR(length=80), server_default=sa.text("current_setting('app.club_uid'::text, true)"), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_canteen_order_club_uid'), ['club_uid'], unique=False)

    with op.batch_alter_table('branch_license', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branch_license_branch_uid'))
        batch_op.create_index(batch_op.f('ix_branch_license_branch_uid'), ['branch_uid'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_branch_license_uid'), ['branch_uid'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('branch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('club_uid', sa.VARCHAR(length=80), server_default=sa.text("current_setting('app.club_uid'::text, true)"), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_branch_club_uid'), ['club_uid'], unique=False)

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('club_uid', sa.VARCHAR(length=80), server_default=sa.text("current_setting('app.club_uid'::text, true)"), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_booking_club_uid'), ['club_uid'], unique=False)

    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('club_uid', sa.VARCHAR(length=80), server_default=sa.text("current_setting('app.club_uid'::text, true)"), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_activity_log_club_uid'), ['club_uid'], unique=False)

    # ### end Alembic commands ###
