"""empty message

Revision ID: d1332c44f0db
Revises: b4b6403c126a
Create Date: 2026-09-20 02:39:53.670799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1332c44f0db'
down_revision = 'b4b6403c126a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_sync_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_sync_id'), ['sync_id'], unique=False)

    # ### end Alembic commands ###
