"""empty message

Revision ID: d3297a70d42f
Revises: 04a428ec9b89
Create Date: 2026-09-03 14:53:56.976854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3297a70d42f'
down_revision = '04a428ec9b89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_bills_dashboard', sa.Boolean(), nullable=True),
    sa.Column('show_bills_canteen', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
