"""empty message

Revision ID: e8c0b64339ad
Revises: 57200e4ceda8
Create Date: 2026-09-06 00:47:33.136938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8c0b64339ad'
down_revision = '57200e4ceda8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.Column('color', sa.String(length=9), nullable=False),
    sa.Column('renderer', sa.String(length=20), nullable=False),
    sa.Column('badge', sa.String(length=6), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table_type')
    # ### end Alembic commands ###
