"""initial_schema

Revision ID: 2e33fd2c9eb5
Revises: 8808f9bcd1b0
Create Date: 2026-09-19 18:54:01.761569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e33fd2c9eb5'
down_revision: Union[str, Sequence[str], None] = '8808f9bcd1b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club', sa.Column('public_url', sa.String(), nullable=True))
    op.drop_index(op.f('ix_club_email'), table_name='club')
    op.drop_column('club', 'password_hash')
    op.drop_column('club', 'phone')
    op.drop_column('club', 'email')
    op.drop_column('club', 'owner_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club', sa.Column('owner_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('club', sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('club', sa.Column('phone', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('club', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_club_email'), 'club', ['email'], unique=True)
    op.drop_column('club', 'public_url')
    # ### end Alembic commands ###
