"""empty message

Revision ID: 39f18936564b
Revises: 2fa49ef79704
Create Date: 2026-09-20 00:28:16.783383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39f18936564b'
down_revision: Union[str, Sequence[str], None] = '2fa49ef79704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('lounge_uid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'lounge_uid')
    # ### end Alembic commands ###
