"""empty message

Revision ID: 46b11739b0fa
Revises: ad6c7eb0db69
Create Date: 2026-09-25 00:07:46.179678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46b11739b0fa'
down_revision: Union[str, Sequence[str], None] = 'ad6c7eb0db69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club', sa.Column('branches', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('club', 'branches')
    # ### end Alembic commands ###
