"""empty message

Revision ID: add3dbbe0b41
Revises: 39f18936564b
Create Date: 2026-09-20 00:37:30.741824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add3dbbe0b41'
down_revision: Union[str, Sequence[str], None] = '39f18936564b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'club_uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('club_uid', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
