"""empty message

Revision ID: d6fa57897621
Revises: add3dbbe0b41
Create Date: 2026-09-20 01:19:30.148266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6fa57897621'
down_revision: Union[str, Sequence[str], None] = 'add3dbbe0b41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('branch_uid', sa.Integer(), nullable=True))
    op.drop_column('booking', 'branch_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('booking', 'branch_uid')
    # ### end Alembic commands ###
